import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import { NeonAuthUIProvider } from "@neondatabase/neon-js/auth/react";
import "@neondatabase/neon-js/ui/css";
import { StrictMode } from "react";
import { authClient } from "@/lib/auth/client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next.JS LMS",
  description: "Generated by Next.JS app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`bg-gray-900 h-full antialiased`}>
        <StrictMode>
          <NeonAuthUIProvider authClient={authClient}>
            <Header>{children}</Header>
            {children}
            <Footer />
          </NeonAuthUIProvider>
        </StrictMode>
      </body>
    </html>
  );
}
